"""empty message

Revision ID: 26abac68da5f
Revises: f703ba684da5
Create Date: 2019-10-03 19:46:49.017120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26abac68da5f'
down_revision = 'f703ba684da5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('link_generation_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'link_generation_time')
    # ### end Alembic commands ###
